### ISSUE TITLE
how to load those saved models to continue training

### ISSUE THREAD

**Issue by church-XP** [marshuang80/gloria#10]
I'm sorry to bother you again

I want to know how do I load those saved models
`./gloria/data/ckpt/pneumothorax_segmentation_0.01/2022_08_03_12_23_46/epoch=35-step=143.ckpt`

What is the difference between this and the pre-trained model
How can I continue my previous training after the training is completed

I have tried replacing the pre-training model directly with epoch=35-step= 143.CKpt
But I found a difference in the size of the two, and it was not successful,

**Comment by marshuang80** [comment]
Hi @church-XP, please see examples for loading saved models [here](https://github.com/marshuang80/gloria/blob/416466af1036294301a872e4da169fefc137a192/gloria/gloria.py#L44), [here](https://github.com/marshuang80/gloria/blob/416466af1036294301a872e4da169fefc137a192/gloria/gloria.py#L97) and [here](https://github.com/marshuang80/gloria/blob/416466af1036294301a872e4da169fefc137a192/gloria/gloria.py#L136). 

As the name suggests, the ckpt file you are referencing to is for segmentation.
