### ISSUE TITLE
Can not download the pretrained model

### ISSUE THREAD

**Issue by Lycus99** [marshuang80/gloria#17]
Hello!
Thanks for your excellent work and model. I want to follow your model and transfer it to another task. However, I can not download the pre-trained ResNet-50 or ResNet-18 weights due to the website proxy or VPN.  Could you please upload the model weights to Google Drive or Aliyundirve? My email address is yc.li@siat.ac.cn. 
Best wishes,
Li

**Comment by luxy1106** [comment]
Hello! 
 As I  experienced the same issues that couldn't download the pre-trained ResNet-50 or ResNet-18 weights. Have you download the model weights until now? If yes, could you share it to me, my email address is luxy1106@126.com. Thank you very much!
Best wishes,
Lu

**Comment by Lycus99** [comment]
The pre-trained models can be download at https://drive.google.com/drive/folders/1ZBfTT7fdoeruqCqxzVUhxET3Iz9EttAA?usp=sharing

**Comment by luxy1106** [comment]
Hello！
Thank you for your reply. I have tried to download the pre-trained models via the website you offered, while it showed with no access permission. I have sent a request for permission following the prompts but I am not sure whether it will work. Do you know how I could gain the access permission definitely?&nbsp; Thank you very much.





Best wishes,
Lu


陌上花开
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marshuang80/gloria"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 下午3:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [marshuang80/gloria] Can not download the pretrained model (Issue #17)





 
The pre-trained models can be download at https://drive.google.com/drive/folders/1ZBfTT7fdoeruqCqxzVUhxET3Iz9EttAA?usp=sharing

**Comment by Lycus99** [comment]
try it again, I have changed the permission.

**Comment by luxy1106** [comment]
Thank you so much!
