### ISSUE TITLE
No such file or directory: '/gloria/CheXpert-v1.0/master_updated.csv'

### ISSUE THREAD

**Issue by zhaozhipeng1997** [marshuang80/gloria#4]
How is this file generated?

**Comment by D-YL** [comment]
I got the same problem, may I ask whether you solve it?

**Comment by marshuang80** [comment]
The master_updated.csv file contains the radiology reports, which include sensitive patient information. To comply with HIPPA, we are currently unable to release this file. We are in the process of anonymizing these reports to prepare for a public release anticipated in the next few months.
