### ISSUE TITLE
The reported results of RSNA dataset

### ISSUE THREAD

**Issue by DopamineLcy** [marshuang80/gloria#6]
Hi~
Thank you very much for your impressive work!
The results of RSNA dataset are quite different from the original paper, I feel confused about this.
Thank you very much if you could explain the reason.
![image](https://user-images.githubusercontent.com/40466246/168457139-de06b5d8-75ef-420e-9a10-e40064119e0c.png)
![image](https://user-images.githubusercontent.com/40466246/168457158-d59cc883-bdef-4098-9465-24094a51ce61.png)

**Comment by marshuang80** [comment]
Hi there, 

thank you for reaching out to clarify! The table you've screenshotted from ConVIRT is based on end-to-end finetuning. For GLoRIA we evaluate our models based on linear probing. Furthermore, we did not have access to ConVIRT's codebase or data split prior to publication. Therefore, the ConVIRT results we included in our paper are based on our own implementation and data split. Hope this helps!
