### ISSUE TITLE
PneumothoraxImageDataset for segmentation 

### ISSUE THREAD

**Issue by DopamineLcy** [marshuang80/gloria#7]
Thank you for your impressive work.
Does PneumothoraxImageDataset includes negative samples? I found the comment
      # only keep positive samples for segmentation
in https://github.com/marshuang80/gloria/blob/8ae01f8cd646dd97c62d0fc10150fb3d509af039/gloria/datasets/image_dataset.py#L185
but I read that code and it looks like that the negative samples are included.
So does it includes negative samples for segmentation and how are the scale (the number of images) of train/val/test sets in your experiments. 
Thank you very much if you could give me the details.

**Comment by marshuang80** [comment]
Hi there, thank you for reaching out regarding this ambiguity. This comment is outdated - we did include both positive and negative examples for our segmentation task. In terms of the number of images, we use a train, valid, and test split of 70/15/15 on the original dataset. Additionally, we reduce the number of negative samples to match the positive ones in the training set.

**Comment by DopamineLcy** [comment]
Thank you very much for your helpful reply.

**Comment by church-XP** [comment]
When I was working on the segmentation task, I ran into a problem:
ValueError: 'a' cannot be empty unless no samples are taken
I want to ask what is this first parameter

**Comment by marshuang80** [comment]
Hi there, can you please a screenshot of the error message?
