### ISSUE TITLE
pretrained code

### ISSUE THREAD

**Issue by lrt666** [marshuang80/gloria#9]
Hi, i am running your pretrained code and I got this error and do you know how to deal with this?
![image](https://user-images.githubusercontent.com/90227639/179906681-e36f4652-e82a-4386-bd5b-5e1faa202787.png)

**Comment by marshuang80** [comment]
Hi there, you are seeing this error because the config is missing the "norm" argument under **model**. I have updated chexpert_pretrain_config.yaml with that configuration ([link](https://github.com/marshuang80/gloria/blob/ffc4fe25dc9e445c8d6964656ecd2c9c433429a6/configs/chexpert_pretrain_config.yaml#L30 )). Can you please check if that solves the problem?

**Comment by lrt666** [comment]
Hi , I still got this error. If I update the config do I need to reinstall the package?

**Comment by marshuang80** [comment]
Which config file are you using?

**Comment by lrt666** [comment]
pretrained config

**Comment by lrt666** [comment]
I just run the pretrained code and I don't find which config I am using.

**Comment by marshuang80** [comment]
Can you confirm that you've pulled the lastest changes and this is the commands you ran: `python run.py -c ./configs/chexpert_pretrain_config.yaml --train
`

**Comment by lrt666** [comment]
No, I am just running the 'Load GLoRIA pretrained models' and I got this error.

**Comment by lrt666** [comment]
If I run the commends 'python run.py -c  #./configs/chexpert_pretrain_config.yaml --train' and I will get error:
![image](https://user-images.githubusercontent.com/90227639/180071517-8ed36f87-9148-4819-9949-4b122426f6c5.png)
Is this normal?

**Comment by marshuang80** [comment]
You'l need to modify CHEXPERT_DATA_DIR in constants.py ([link](https://github.com/marshuang80/gloria/blob/ffc4fe25dc9e445c8d6964656ecd2c9c433429a6/gloria/constants.py#L4)) to point to your chexpert data directory to avoid the "FileNotFoundError"

**Comment by marshuang80** [comment]
Thank you for helping me debug the error. I've made some changes - can you pull the repo again and try load GLoRIA pretrained models again?

**Comment by lrt666** [comment]
Solved with the previous error but there is a new error:
![image](https://user-images.githubusercontent.com/90227639/180078934-1069d26d-2d6d-403b-9ed9-477ba296e52a.png)

**Comment by marshuang80** [comment]
Made new changes - how about now?

**Comment by lrt666** [comment]
still got error:
![image](https://user-images.githubusercontent.com/90227639/180097306-5fcf7aaf-3837-4f0b-8447-f81f593924e5.png)

**Comment by marshuang80** [comment]
My apologies, how about now?

**Comment by lrt666** [comment]
got error:
![image](https://user-images.githubusercontent.com/90227639/180294116-282894c9-5be6-41f9-b88c-a5c6637b4226.png)

**Comment by marshuang80** [comment]
How about now

**Comment by lrt666** [comment]
![image](https://user-images.githubusercontent.com/90227639/180296425-11fa6cdb-0b9f-4197-8be7-1862c3fb6882.png)
Is this a typo or other error?

**Comment by marshuang80** [comment]
typo, thank you for your help

**Comment by ruitaoliu666** [comment]
Thanks for your patience and can I know where to download chexpert?

**Comment by marshuang80** [comment]
Please refer to this link for more information on CheXpert: https://stanfordmlgroup.github.io/competitions/chexpert/

Just a heads up - the CheXpert reports are still under review to ensure HIPPA compliance and patient privacy; hence not publicly accessible yet.

**Comment by zyt0211** [comment]
Thank you for your outstanding work! May I ask when master_updated.csv will be published, or can you tell me what parts it consists of? Looking forward to your reply!
